### PR TITLE
test: run tests before committing, in addition to `pretty-quick`

### LINKED ISSUE #60: Check commit messages before committing
Working on #59, I've noted that the commit messages are not validated locally during the commit. I had failing commit messages and only found out when the workflow ran on my PR. I think it'd be nice to have it run during the commit as well, with `'commit-msg': 'commitlint -E HUSKY_GIT_PARAMS',` in `husky` hooks for example.

Would you accept PR for this?

One other idea is to run the tests as well before committing, for example using [`lint-staged`](https://github.com/okonet/lint-staged). Would be happy to discuss that here and see your thoughts, and include it in a PR if desired.

### PR DESCRIPTION
**Pull request by jdbruijn**
`pretty-quick` is not needed any more as lint-staged can run prettier with just the staged files, thus getting the same behaviour.

Closes #60.

### CODE REVIEW

File: .lintstagedrc.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+module.exports = {
+  '*.{ts,tsx,vue,css,less,scss,html,htm,md,markdown}': 'prettier --write',
```
Comment (wagoid) [inline .lintstagedrc.js:2]: The project doesn't have Typescript files, are they included here to be future proof?

**Review by wagoid — APPROVED** [review]
Thanks for the update! You now have conflicts on `package.json`, could you fix them?

File: .lintstagedrc.js (hunk 1 above)
Comment (jdbruijn) [reply .lintstagedrc.js:2]: Yes, these are the supported formats of Prettier so I just included all of them. It doesn't matter if some formats are not, yet, used in this repo.

**Comment by jdbruijn** [comment]
@wagoid  Conflicts are resolved now.
